geting and adding attachments
Arky9782/chat pull request #9
Opened 2017-12-08 11:39 UTC by Arky9782

2017-12-08 14:01 UTC, fesor requested changes

2017-12-08 14:01 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +            $fileName = 'chat.dev/files_directory/'.md5(uniqid()) . '.' . $uploadedFile->guessExtension();
https://en.wikipedia.org/wiki/Separation_of_concerns

2017-12-08 14:01 UTC, fesor commented on src/AppBundle/Entity/Chat_user.php
> +     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Message", mappedBy="chatUser")
`Chat_user`???

2017-12-08 14:45 UTC, Arky9782 commented on src/AppBundle/Entity/Chat_user.php
> +     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Message", mappedBy="chatUser")
User is reserved by postgres)

2017-12-08 14:45 UTC, Arky9782 commented on src/AppBundle/Entity/Chat_user.php
> +     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Message", mappedBy="chatUser")
User is reserved by postgres)

2017-12-08 14:47 UTC, Arky9782 commented on src/AppBundle/Controller/DefaultController.php
> +            $fileName = 'chat.dev/files_directory/'.md5(uniqid()) . '.' . $uploadedFile->guessExtension();
? Need to separate this to more controllers?)

2017-12-08 15:34 UTC, fesor commented on src/AppBundle/Entity/Chat_user.php
> +     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Message", mappedBy="chatUser")
1. Camel Case
2. you could specify table name "users".

2017-12-08 15:34 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +            $fileName = 'chat.dev/files_directory/'.md5(uniqid()) . '.' . $uploadedFile->guessExtension();
You have several concerns:

 - generate file name
 - generate url
 - upload file

https://symfony.com/doc/current/service_container.html

2017-12-14 16:15 UTC, enleur commented on app/config/security.yml
> +        AppBundle\Entity\Users: bcrypt
User же

2017-12-14 16:16 UTC, enleur commented on src/AppBundle/Controller/DefaultController.php
> +    public function getMessagesAction(Flush $flush,EntityManager $em, SerializerInterface $serializer)
EntityManagerInterface

2017-12-14 16:16 UTC, enleur commented on src/AppBundle/Controller/DefaultController.php
> +        $messages = $this->getDoctrine()->getRepository('AppBundle:Message')->getMessages($em, $serializer);
зачем тебе $em если ты делаешь $this->getDoctrine в этом же методе?

2017-12-14 16:16 UTC, enleur commented on src/AppBundle/Controller/DefaultController.php
> +        $messages = $this->getDoctrine()->getRepository('AppBundle:Message')->getMessages($em, $serializer);
getMessages с дабл диспатчем, зачем?

2017-12-14 16:17 UTC, enleur commented on src/AppBundle/Controller/DefaultController.php
> +    public function postAction(UrlGen $urlGen, FileNameGen $fileNameGen, Persist $persist, Flush $flush, SerializerInterface $serializer, Request $request)
Persist, Flush? @fesor твоя затея небось?

2017-12-14 16:18 UTC, enleur commented on src/AppBundle/Controller/RegistrationController.php
> +            return new Response('Registration successful',201);
для http кодов есть константы \Symfony\Component\HttpFoundation\Response

2017-12-14 16:18 UTC, enleur commented on src/AppBundle/Entity/Message.php
> +    public function setReadAt()
шо это?

2017-12-14 16:18 UTC, enleur commented on src/AppBundle/Entity/Users.php
> + * @ORM\Entity(repositoryClass="AppBundle\Repository\usersRepository")
UserRepository

2017-12-14 16:18 UTC, enleur commented on src/AppBundle/Entity/Users.php
> +        return $this;
https://ocramius.github.io/blog/fluent-interfaces-are-evil/

2017-12-14 16:19 UTC, enleur commented on src/AppBundle/Repository/MessageRepository.php
> +        $dql = "SELECT u.username, a.file, m FROM AppBundle:Message m INNER JOIN m.chatUser u INNER JOIN m.attachment a";
почему не query builder?

2017-12-14 16:19 UTC, enleur commented on src/AppBundle/Repository/MessageRepository.php
> +            ->setMaxResults(20);
maxResults с джоинами делает забавные вещи

2017-12-14 16:20 UTC, enleur commented on src/AppBundle/Repository/MessageRepository.php
> +        return new JsonResponse($arr);
JsonResponse в репозитории? rly?

2017-12-14 16:20 UTC, enleur commented on src/AppBundle/Repository/MessageRepository.php
> +             $arr[] = $jsonResponse = $serializer->serialize($messages, 'json');
да и нахер тут сериалайзер?

2017-12-14 16:21 UTC, enleur commented on src/AppBundle/Services/FileNameGen.php
> +        $filename = md5(uniqid()).'.'.$_FILES['file']['name'];
$_FILES['file']['name'] - wtf?

2017-12-14 16:21 UTC, enleur commented on src/AppBundle/Services/UrlGen.php
> +class UrlGen
в чем смысл этого "сервиса"?

2017-12-14 16:33 UTC, akovalyov commented on src/AppBundle/Controller/DefaultController.php
> +use AppBundle\Repository\usersRepository;
CamelCase

2017-12-14 17:01 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +    public function getMessagesAction(Flush $flush,EntityManager $em, SerializerInterface $serializer)
скорее "заменить на репозиторий".

2017-12-14 17:01 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +        $messages = $this->getDoctrine()->getRepository('AppBundle:Message')->getMessages($em, $serializer);
это называется "культ карго". Он скорее всего увидел это где-то в каких-то доках, и в целом до сих пор не понимает что тут происходит.

2017-12-14 17:02 UTC, fesor commented on src/AppBundle/Controller/RegistrationController.php
>          $form = $this->createForm(UserType::class, $user);
какие к черту формы?

2017-12-14 17:03 UTC, fesor commented on src/AppBundle/Entity/Users.php
> +        return $this;
это вопервых, а во вторых - у тебя добавятся скоро каналы, так что одной меткой на юзера ты не отделаешься.

2017-12-14 17:04 UTC, fesor commented on src/AppBundle/Repository/MessageRepository.php
> +            ->setMaxResults(20);
просто попроси его добавить тест кейс где у каждого сообщения по два аттачментаю

2017-12-14 17:06 UTC, Arky9782 commented on src/AppBundle/Controller/DefaultController.php
> +        $messages = $this->getDoctrine()->getRepository('AppBundle:Message')->getMessages($em, $serializer);
@enleur ты про return'ы? Если да, то не знаю как по-другому получить инфу из метода) А $em пофиксил инжектом в класс)

2017-12-14 17:07 UTC, Arky9782 commented on src/AppBundle/Controller/DefaultController.php
> +        $messages = $this->getDoctrine()->getRepository('AppBundle:Message')->getMessages($em, $serializer);
@fesor зафигачил сам чтоб работало)

2017-12-14 17:07 UTC, Arky9782 commented on src/AppBundle/Controller/RegistrationController.php
>          $form = $this->createForm(UserType::class, $user);
@fesor html страничка с регой) Не пойдет?)

2017-12-14 17:10 UTC, Arky9782 commented on src/AppBundle/Repository/MessageRepository.php
> +            ->setMaxResults(20);
@fesor два аттачмента?) Я рассчитывал на один только)

2017-12-14 19:52 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +    public function postAction(UrlGen $urlGen, FileNameGen $fileNameGen, Persist $persist, Flush $flush, SerializerInterface $serializer, Request $request)
с Flush - да, с Persist - не моя. Я ему уже 10 раз говорил репозиторий прокинуть

2017-12-14 19:52 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +    public function postAction(UrlGen $urlGen, FileNameGen $fileNameGen, Persist $persist, Flush $flush, SerializerInterface $serializer, Request $request)
И FileNameGen внутрь аплоадера.... ну короч что-то не так пошло

2017-12-14 19:53 UTC, fesor commented on src/AppBundle/Entity/Message.php
> +    public function setReadAt()
это он типа курсор сделал для отметки какое сообщение было прочитано последним. К сожалению нужно это было как минимум по другому назвать и уж явно не в юзере хранить.

2017-12-14 19:54 UTC, fesor commented on src/AppBundle/Repository/MessageRepository.php
> +            ->setMaxResults(20);
1. аттачменты загружаются отдельно.
2. аттачменты грузятся не мультипартом
3. аттачментов может быть много и с разным типом (у одного сообщения может быть и текст, и картинка и аудио например, аля "наорать на суппорт").

2017-12-14 19:54 UTC, fesor commented on src/AppBundle/Controller/RegistrationController.php
>          $form = $this->createForm(UserType::class, $user);
не пойдет.

2017-12-14 20:54 UTC, Arky9782 commented on src/AppBundle/Services/FileNameGen.php
> +        $filename = md5(uniqid()).'.'.$_FILES['file']['name'];
@enleur получаю имя файла)

2017-12-14 20:56 UTC, Arky9782 commented on src/AppBundle/Controller/RegistrationController.php
>          $form = $this->createForm(UserType::class, $user);
@fesor Но симфони так не умеет вроде (

2017-12-14 21:21 UTC, akovalyov commented on src/AppBundle/Services/FileNameGen.php
> +        $filename = md5(uniqid()).'.'.$_FILES['file']['name'];
@Arky9782 тут сразу несколько проблем.
1. md5 deprecated
2. .используются superglobals, которые уже лет 10 как использовать моветон
3. Твой сервис теперь знает про HTTP. Дальше слоя контроллеров это утекать не должно.

2017-12-14 21:23 UTC, akovalyov commented on src/AppBundle/Controller/DefaultController.php
> +        $messages = $this->getDoctrine()->getRepository('AppBundle:Message')->getMessages($em, $serializer);
@Arky9782 задача репозитория - вернуть данные. Серилизация - не его ответственность.

2017-12-14 21:23 UTC, akovalyov commented on src/AppBundle/Controller/DefaultController.php
> +            $attachment->setFile($URL);
lowercase

2017-12-14 21:24 UTC, akovalyov commented on src/AppBundle/Entity/Attachment.php
> +     * @ORM\Column(name="file", type="string", length=255)
это file или filename?

2017-12-14 21:25 UTC, akovalyov commented on src/AppBundle/Entity/Users.php
> +        return $this;
ну и `now` - default value for DateTime.

2017-12-15 04:05 UTC, Arky9782 commented on src/AppBundle/Services/FileNameGen.php
> +        $filename = md5(uniqid()).'.'.$_FILES['file']['name'];
@akovalyov Чем можно заменить superglobals?

2017-12-15 06:14 UTC, akovalyov commented on src/AppBundle/Services/FileNameGen.php
> +        $filename = md5(uniqid()).'.'.$_FILES['file']['name'];
@Arky9782 я бы вообще выкинул этот сервис (как и соседний) и генерил имя файла в контроллере, потому что как минимум тут нужно переименовать класс, метод, убрать мусорные аннотации из начала файла - короче много работы. Ну или сделал бы отдельный сервис-аплоадер, который будет брать твой файл, генерить ему имя и загружать куда надо. Вообще можно его сделать как Factory, который будет хендлить файл, создавать твой Attachment с правильно заполнеными полями и возвращать его.
Ну а по твоему изначальному вопросу -- можно было передавать сюда `uploadedFile` из контроллера.

2017-12-15 14:47 UTC, fesor commented on src/AppBundle/Controller/RegistrationController.php
>          $form = $this->createForm(UserType::class, $user);
это регистрация, причем тут симфони?

2017-12-16 15:21 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +        $messages = $this->getDoctrine()->getRepository('AppBundle:Message')->getMessages();
Ты сделал свой репозиторий?

2017-12-16 15:21 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +    public function postAction(FileFactory $fileFactory, Persist $persist, Flush $flush, SerializerInterface $serializer, Request $request)
но это загрузчик а не фабрика

2017-12-16 15:21 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +        if($uploadedFile = $request->files->get('file'))
1. вынести аплоад в отдельный метод
2. что мы говорили на счет мультипартов?

2017-12-16 15:22 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +            $url = $fileFactory->getFile($uploadedFile);
хранить в базе ты должен относительный путь, по которому сгенеришь урл. А уже генерация урлов - это отдельная штука. Ей на вход только относительный путь и надо давать.

2017-12-16 15:23 UTC, fesor commented on src/AppBundle/Services/FileFactory.php
> +        return $url;
это не `$url` а `$path` тогда.

2017-12-16 17:55 UTC, Arky9782 commented on src/AppBundle/Controller/DefaultController.php
> +        if($uploadedFile = $request->files->get('file'))
@fesor 
1. Куда этот метод поместить?)
2. Что мы их не используем. А здесь есть что-то связанное с мультипартом?)

2017-12-16 17:56 UTC, Arky9782 commented on src/AppBundle/Controller/DefaultController.php
> +            $url = $fileFactory->getFile($uploadedFile);
@fesor Вернуть обратно сервис urlGen?)

2017-12-16 17:58 UTC, Arky9782 commented on src/AppBundle/Controller/DefaultController.php
> +    public function postAction(FileFactory $fileFactory, Persist $persist, Flush $flush, SerializerInterface $serializer, Request $request)
@fesor решил попафоснее))) Ладно, в след коммите пофикшу)

2017-12-16 18:06 UTC, Arky9782 commented on src/AppBundle/Controller/DefaultController.php
> +        $messages = $this->getDoctrine()->getRepository('AppBundle:Message')->getMessages();
@fesor Заполнил пустой репозиторий

2017-12-19 12:16 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +        if($uploadedFile = $request->files->get('file'))
1. отдельный метод апишки. Что бы при создании месседжа уже все готовое приходило.
2. `$request->files->get('file')` - покажи как ты это без мультипарта делаешь

2017-12-19 12:16 UTC, fesor commented on src/AppBundle/Controller/RegistrationController.php
> +        $persist($user);
репозиторий!

2017-12-19 12:17 UTC, fesor commented on src/AppBundle/Entity/Channel.php
> +     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\User", inversedBy="channels")
зачем пользователям знать о своих каналах? Тем более у тебя есть `Participant`.

2017-12-19 12:17 UTC, fesor commented on src/AppBundle/Entity/Participant.php
> +        return $this;
не нужен тебе тут чейнинг методов.

2017-12-19 12:18 UTC, fesor commented on src/AppBundle/Entity/User.php
> +        $this->setPassword(crypt('',133232));
то есть ты заинджектил энкодер паролей но не юзаешь его?

Да и потом - password_hash функция. Иди читай зачем она и почему только так.

2017-12-19 12:18 UTC, fesor commented on src/AppBundle/Entity/User.php
> +        $this->setUsername('');
что это?

2017-12-19 12:19 UTC, fesor commented on src/AppBundle/Entity/User.php
>      public function getRoles()
тебе не нужен `UserInterface` если что. От слова совсем.

2017-12-19 12:19 UTC, fesor commented on src/AppBundle/Repository/MessageRepository.php
> +            ->select('m.body','m.createdAt','m.id', 'a.file', 'u.username','u.channels')
зачем тебе каналы пользователя, если тебе надо список сообщений?

2017-12-19 12:20 UTC, fesor commented on src/AppBundle/Repository/Persist.php
> +class Persist
этот сервис не нужен. Удали его.

2017-12-19 12:20 UTC, fesor commented on src/AppBundle/Repository/UserRepository.php
> +class UserRepository extends \Doctrine\ORM\EntityRepository
не надо экстендиться от `EntityRepository`. Просто сервис. Со своим интерфейсом. Иначе как бы нет смысла его вводить.

2017-12-19 12:25 UTC, Arky9782 commented on src/AppBundle/Repository/MessageRepository.php
> +            ->select('m.body','m.createdAt','m.id', 'a.file', 'u.username','u.channels')
@fesor почему сломана?)

2017-12-19 12:29 UTC, Arky9782 commented on src/AppBundle/Entity/User.php
> +        $this->setPassword(crypt('',133232));
@fesor юзаю, просто забыл почистить конструктор)

2017-12-19 12:32 UTC, Arky9782 commented on src/AppBundle/Entity/Participant.php
> +        return $this;
@fesor чейнинг?)

2017-12-19 12:33 UTC, Arky9782 commented on src/AppBundle/Controller/RegistrationController.php
> +        $persist($user);
@fesor из-за экстенда от EntityRepository это не работало)

2017-12-19 13:43 UTC, fesor commented on src/AppBundle/Repository/MessageRepository.php
> +            ->select('m.body','m.createdAt','m.id', 'a.file', 'u.username','u.channels')
а ты потести: когда есть несколько каналов у юзера, несколько файлов у чата и т.д.

2017-12-19 17:19 UTC, Arky9782 commented on src/AppBundle/Repository/MessageRepository.php
> +            ->select('m.body','m.createdAt','m.id', 'a.file', 'u.username','u.channels')
@fesor Что же делать в таком случае?

2017-12-20 11:40 UTC, fesor commented on src/AppBundle/Repository/MessageRepository.php
> +            ->select('m.body','m.createdAt','m.id', 'a.file', 'u.username','u.channels')
1. зачем тебе джойн на `u.channels`?
2. зачем хранить файлы как релейшены? В данном случае достаточно хранить из в jsonb.

2017-12-20 11:41 UTC, fesor commented on src/AppBundle/Entity/Participant.php
> +        return $this;
google "method chaining"

2017-12-20 11:43 UTC, fesor commented on src/AppBundle/Controller/RegistrationController.php
> +        $persist($user);
1. это твой метод
2. мы уже обсуждали что не надо от него наследоваться. Наша цель - заменить интерфейсы общего назначения (EntityManagerInterface которому пофиг на то с какой сущностью работать) на интерфейсы специализированные (которым не пофиг). Это позволит сильно упростить код и уменьшить связанность, проще будет вносить изменения и т.д.

2017-12-20 16:56 UTC, Arky9782 commented on src/AppBundle/Repository/MessageRepository.php
> +            ->select('m.body','m.createdAt','m.id', 'a.file', 'u.username','u.channels')
@fesor в первом запросе забираем все сообщения, а во втором все файлы без связей? Или со связями? Если со свяхями, то я не знаю как это сделать, думаю что там можно вытянуть из qb полученные айди сообщений и уже по ним найти файлы связанные с этим айди. Но неизвестно могу ли я вообще взять полученные айди, и даже если можно, то взять больше одного я вроде бы не смогу. Как быть? (

2017-12-20 17:42 UTC, Arky9782 commented on src/AppBundle/Controller/RegistrationController.php
> +        $persist($user);
@fesor когда убрал от него наследование, то отвалилась аутификация  (

2017-12-20 17:43 UTC, Arky9782 commented on src/AppBundle/Controller/RegistrationController.php
> +        $persist($user);
@fesor убрал этот репозиторий из сущности и теперь все нормально)

2017-12-20 18:51 UTC, Arky9782 commented on src/AppBundle/Repository/MessageRepository.php
> +            ->select('m.body','m.createdAt','m.id', 'a.file', 'u.username','u.channels')
@fesor Мучился с qb, но так ничего и не получилось. Пагинатор два FROM не поддерживает (

2017-12-21 05:37 UTC, Arky9782 commented on src/AppBundle/Repository/MessageRepository.php
> +            ->select('m.body','m.createdAt','m.id', 'a.file', 'u.username','u.channels')
@fesor А если сделать объединение спомощью WHERE?

2017-12-22 18:02 UTC, fesor commented on src/AppBundle/Controller/DefaultController.php
> +    public function getMessagesAction(Flush $flush,EntityManagerInterface $em, SerializerInterface $serializer)
если у тебя есть репозиторий и `Flush` то тебе не нужен `EntityManagerInterface`.

2017-12-22 18:03 UTC, fesor commented on src/AppBundle/Repository/UserRepository.php
> +    public function add($data)
что в слове "специализированный" тебе непонятно?

```
public function add(User $user);
```

2017-12-22 18:03 UTC, fesor commented on src/AppBundle/Repository/MessageRepository.php
> +        $dql = "SELECT m, u, m.id, m.body, m.createdAt, u.username,(SELECT a.file FROM AppBundle:Attachment a WHERE a.id = m.id) FROM AppBundle:Message m JOIN m.User u";
что это?

2017-12-25 13:23 UTC, merged